// String jsony={"responseObject": {
//   "totalCount": "8",
//   "pageCount": "1",
//   "pageSize": "10",
//   "recordList": [
//     {
//       "id": "45",
//       "invited": "1",
//       "betName": "Champions League Final 2023",
//       "description": "UEFA Champions League Final 2023 between Manchester City and Inter Milan",
//       "coverImage": "",
//       "startDate": "09/12/2023",
//       "startTime": "08:59",
//       "endDate": "",
//       "endTime": "",
//       "amount": "67",
//       "judgeUser": "2",
//       "wonBy": "0",
//       "createdBy": "48",
//       "status": "PENDING_INVITATION",
//       "createdOn": "2023-09-12T03:29:13Z",
//       "updatedOn": null,
//       "createdByUser": "Ajay ((981) 087-3985)",
//       "invitedMobile": "(999) 942-3173",
//       "invitedUser": {
//         "userId": "1",
//         "firstName": "Vibhor",
//         "lastName": "Gupta",
//         "mobile": "(999) 942-3173",
//         "email": "vibhor@mobiquel.com",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-07-06T11:54:12Z",
//         "updatedOn": null,
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       },
//       "invitedByUser": {
//         "userId": "48",
//         "firstName": "Ajay",
//         "lastName": "Gupta",
//         "mobile": "(981) 087-3985",
//         "email": "ajay@weekendr.in",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-09-07T16:03:33Z",
//         "updatedOn": null,
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       }
//     },
//     {
//       "id": "38",
//       "invited": "1",
//       "betName": "Champions League Final 2023",
//       "description": "UEFA Champions League Final 2023 between Manchester City and Inter Milan",
//       "coverImage": "",
//       "startDate": "07/15/2023",
//       "startTime": "23:38",
//       "endDate": "",
//       "endTime": "",
//       "amount": "123",
//       "judgeUser": "2",
//       "wonBy": "0",
//       "createdBy": "9",
//       "status": "PENDING_INVITATION",
//       "createdOn": "2023-09-11T16:36:18Z",
//       "updatedOn": null,
//       "createdByUser": "Philip ((123) 891-23)",
//       "invitedMobile": "(999) 942-3173",
//       "invitedUser": {
//         "userId": "1",
//         "firstName": "Vibhor",
//         "lastName": "Gupta",
//         "mobile": "(999) 942-3173",
//         "email": "vibhor@mobiquel.com",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-07-06T11:54:12Z",
//         "updatedOn": null,
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       },
//       "invitedByUser": {
//         "userId": "9",
//         "firstName": "Philip",
//         "lastName": "John",
//         "mobile": "(123) 891-23",
//         "email": "philip@mailinator.com",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-07-20T16:16:45Z",
//         "updatedOn": "2023-08-28T17:38:06Z",
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       }
//     },
//     {
//       "id": "17",
//       "invited": "1",
//       "betName": "Champions League Final 2023",
//       "description": "UEFA Champions League Final 2023 between Manchester City and Inter Milan",
//       "coverImage": "https://wallpapercave.com/wp/RE0fHtC.jpg",
//       "startDate": "07/15/2023",
//       "startTime": "",
//       "endDate": "07/29/2023",
//       "endTime": "",
//       "amount": "10",
//       "judgeUser": "2",
//       "wonBy": "0",
//       "createdBy": "50",
//       "status": "PENDING_INVITATION",
//       "createdOn": "2023-09-08T18:06:50Z",
//       "updatedOn": null,
//       "createdByUser": "tripti ((965) 480-1581)",
//       "invitedMobile": "(999) 942-3173",
//       "invitedUser": {
//         "userId": "1",
//         "firstName": "Vibhor",
//         "lastName": "Gupta",
//         "mobile": "(999) 942-3173",
//         "email": "vibhor@mobiquel.com",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-07-06T11:54:12Z",
//         "updatedOn": null,
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       },
//       "invitedByUser": {
//         "userId": "50",
//         "firstName": "tripti",
//         "lastName": "gupta",
//         "mobile": "(965) 480-1581",
//         "email": "tripti.dssw@gmail.com",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-09-08T17:53:55Z",
//         "updatedOn": null,
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       }
//     },
//     {
//       "id": "12",
//       "invited": "1",
//       "betName": "Champions League Final 2023",
//       "description": "UEFA Champions League Final 2023 between Manchester City and Inter Milan",
//       "coverImage": "https://wallpapercave.com/wp/RE0fHtC.jpg",
//       "startDate": "07/15/2023",
//       "startTime": "",
//       "endDate": "07/29/2023",
//       "endTime": "",
//       "amount": "100",
//       "judgeUser": "2",
//       "wonBy": "0",
//       "createdBy": "48",
//       "status": "PENDING_INVITATION",
//       "createdOn": "2023-09-08T17:30:34Z",
//       "updatedOn": null,
//       "createdByUser": "Ajay ((981) 087-3985)",
//       "invitedMobile": "(999) 942-3173",
//       "invitedUser": {
//         "userId": "1",
//         "firstName": "Vibhor",
//         "lastName": "Gupta",
//         "mobile": "(999) 942-3173",
//         "email": "vibhor@mobiquel.com",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-07-06T11:54:12Z",
//         "updatedOn": null,
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       },
//       "invitedByUser": {
//         "userId": "48",
//         "firstName": "Ajay",
//         "lastName": "Gupta",
//         "mobile": "(981) 087-3985",
//         "email": "ajay@weekendr.in",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-09-07T16:03:33Z",
//         "updatedOn": null,
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       }
//     },
//     {
//       "id": "11",
//       "invited": "1",
//       "betName": "Champions League Final 2023",
//       "description": "UEFA Champions League Final 2023 between Manchester City and Inter Milan",
//       "coverImage": "https://wallpapercave.com/wp/RE0fHtC.jpg",
//       "startDate": "07/15/2023",
//       "startTime": "",
//       "endDate": "07/29/2023",
//       "endTime": "",
//       "amount": "3131",
//       "judgeUser": "2",
//       "wonBy": "0",
//       "createdBy": "9",
//       "status": "PENDING_INVITATION",
//       "createdOn": "2023-09-08T17:02:42Z",
//       "updatedOn": null,
//       "createdByUser": "Philip ((123) 891-23)",
//       "invitedMobile": "(999) 942-3173",
//       "invitedUser": {
//         "userId": "1",
//         "firstName": "Vibhor",
//         "lastName": "Gupta",
//         "mobile": "(999) 942-3173",
//         "email": "vibhor@mobiquel.com",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-07-06T11:54:12Z",
//         "updatedOn": null,
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       },
//       "invitedByUser": {
//         "userId": "9",
//         "firstName": "Philip",
//         "lastName": "John",
//         "mobile": "(123) 891-23",
//         "email": "philip@mailinator.com",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-07-20T16:16:45Z",
//         "updatedOn": "2023-08-28T17:38:06Z",
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       }
//     },
//     {
//       "id": "5",
//       "invited": "1",
//       "betName": "Champions League Final 2023",
//       "description": "UEFA Champions League Final 2023 between Manchester City and Inter Milan",
//       "coverImage": "http://139.59.81.101/utebi/uploads/bet_cover/image_cropper_1694098527966_1694161127431.jpg",
//       "startDate": "07/15/2023",
//       "startTime": "",
//       "endDate": "07/29/2023",
//       "endTime": "",
//       "amount": "100",
//       "judgeUser": "2",
//       "wonBy": "0",
//       "createdBy": "48",
//       "status": "PENDING_INVITATION",
//       "createdOn": "2023-09-08T08:18:53Z",
//       "updatedOn": null,
//       "createdByUser": "Ajay ((981) 087-3985)",
//       "invitedMobile": "(999) 942-3173",
//       "invitedUser": {
//         "userId": "1",
//         "firstName": "Vibhor",
//         "lastName": "Gupta",
//         "mobile": "(999) 942-3173",
//         "email": "vibhor@mobiquel.com",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-07-06T11:54:12Z",
//         "updatedOn": null,
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       },
//       "invitedByUser": {
//         "userId": "48",
//         "firstName": "Ajay",
//         "lastName": "Gupta",
//         "mobile": "(981) 087-3985",
//         "email": "ajay@weekendr.in",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-09-07T16:03:33Z",
//         "updatedOn": null,
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       }
//     },
//     {
//       "id": "4",
//       "invited": "1",
//       "betName": "Champions League Final 2023",
//       "description": "UEFA Champions League Final 2023 between Manchester City and Inter Milan",
//       "coverImage": "https://wallpapercave.com/wp/RE0fHtC.jpg",
//       "startDate": "09/08/2023",
//       "startTime": "01:36",
//       "endDate": "07/29/2023",
//       "endTime": "",
//       "amount": "100",
//       "judgeUser": "2",
//       "wonBy": "0",
//       "createdBy": "48",
//       "status": "PENDING_INVITATION",
//       "createdOn": "2023-09-08T08:07:12Z",
//       "updatedOn": null,
//       "createdByUser": "Ajay ((981) 087-3985)",
//       "invitedMobile": "(999) 942-3173",
//       "invitedUser": {
//         "userId": "1",
//         "firstName": "Vibhor",
//         "lastName": "Gupta",
//         "mobile": "(999) 942-3173",
//         "email": "vibhor@mobiquel.com",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-07-06T11:54:12Z",
//         "updatedOn": null,
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       },
//       "invitedByUser": {
//         "userId": "48",
//         "firstName": "Ajay",
//         "lastName": "Gupta",
//         "mobile": "(981) 087-3985",
//         "email": "ajay@weekendr.in",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-09-07T16:03:33Z",
//         "updatedOn": null,
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       }
//     },
//     {
//       "id": "3",
//       "invited": "1",
//       "betName": "Champions League Final 2023",
//       "description": "UEFA Champions League Final 2023 between Manchester City and Inter Milan",
//       "coverImage": "https://wallpapercave.com/wp/RE0fHtC.jpg",
//       "startDate": "07/15/2023",
//       "startTime": "",
//       "endDate": "07/29/2023",
//       "endTime": "",
//       "amount": "32423",
//       "judgeUser": "2",
//       "wonBy": "0",
//       "createdBy": "9",
//       "status": "PENDING_INVITATION",
//       "createdOn": "2023-09-07T19:09:36Z",
//       "updatedOn": null,
//       "createdByUser": "Philip ((123) 891-23)",
//       "invitedMobile": "(999) 942-3173",
//       "invitedUser": {
//         "userId": "1",
//         "firstName": "Vibhor",
//         "lastName": "Gupta",
//         "mobile": "(999) 942-3173",
//         "email": "vibhor@mobiquel.com",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-07-06T11:54:12Z",
//         "updatedOn": null,
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       },
//       "invitedByUser": {
//         "userId": "9",
//         "firstName": "Philip",
//         "lastName": "John",
//         "mobile": "(123) 891-23",
//         "email": "philip@mailinator.com",
//         "password": null,
//         "deviceOS": "Android",
//         "createdOn": "2023-07-20T16:16:45Z",
//         "updatedOn": "2023-08-28T17:38:06Z",
//         "pushNotificationId": "XXXXXX",
//         "token": null
//       }
//     }
//   ]
// },
//   "errorCode": 0,
//   "errorMessage": "Success"
// } ;
//
// Map<String, dynamic> data = {
//   'level1_1': {
//     'item1': 'value1',
//     'item2': 'value2',
//     'item3': 'value3',
//     'item4': 'value4',
//     'item5': 'value5',
//   },
//   'level1_2': {
//     'item1': 'value1',
//     'item2': 'value2',
//     'item3': 'value3',
//     'item4': 'value4',
//     'item5': 'value5',
//   },
//   'level1_3': {
//     'item1': 'value1',
//     'item2': 'value2',
//     'item3': 'value3',
//     'item4': 'value4',
//     'item5': 'value5',
//   },
// };